name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node modules cache
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn
      - run: yarn lint
      - run: yarn test
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: yarn build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain https://checkout-task-xyz.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}

